version: "3"
services:
  database:
    container_name: clickhouse-ssp
    image: clickhouse/clickhouse-server:23.9
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ${PWD}/clickhouse-server/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/clickhouse-server/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"
