version: "3"
services:
  database:
    container_name: clickhouse-ssp
    image: clickhouse/clickhouse-server:23.9
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ${PWD}/clickhouse-server:/etc/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"
